drop SEQUENCE x_seq_documents;
drop SEQUENCE x_seq_docenum;
drop TABLE x_doc_fields;
drop TABLE x_doc_enums;
drop TABLE x_representatives ;
drop TABLE x_taxpayers ;
drop TABLE x_documents;
drop TABLE xml_staging;

-- MAIN
CREATE TABLE x_documents (
    doc_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staging_id    NUMBER,
    reason        VARCHAR2(500),
    email         VARCHAR2(200),
    has_rep       CHAR(1) CHECK (has_rep IN ('Y','N')),
    created_at    DATE DEFAULT SYSDATE
);

-- TAXPAYER
CREATE TABLE x_taxpayers (
    taxpayer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id        NUMBER NOT NULL,
    name          VARCHAR2(200),
    egn           VARCHAR2(10),
    type          NUMBER(1) CHECK (type IN (1,2)),
    bulstat       VARCHAR2(10),
    address       VARCHAR2(500),
    CONSTRAINT fk_taxpayer_doc FOREIGN KEY (doc_id)
        REFERENCES x_documents(doc_id)
);

-- REPRESENTATIVE
CREATE TABLE x_representatives (
    rep_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id        NUMBER NOT NULL,
    name          VARCHAR2(200),
    egn           VARCHAR2(10),
    type          NUMBER(1) CHECK (type IN (1,2)),
    CONSTRAINT fk_rep_doc FOREIGN KEY (doc_id)
        REFERENCES x_documents(doc_id)
);

-- DOCENUM
CREATE TABLE x_doc_enums (
    docenum_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id        NUMBER NOT NULL,
    ext_id        VARCHAR2(100),
    CONSTRAINT fk_docenum_doc FOREIGN KEY (doc_id)
        REFERENCES x_documents(doc_id)
);

-- FIELDS
CREATE TABLE x_doc_fields (
    field_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    docenum_id    NUMBER NOT NULL,
    name          VARCHAR2(200),
    value         VARCHAR2(500),
    CONSTRAINT fk_field_docenum FOREIGN KEY (docenum_id)
        REFERENCES x_doc_enums(docenum_id)
);

CREATE SEQUENCE x_seq_documents START WITH 1;
CREATE SEQUENCE x_seq_docenum START WITH 1;

CREATE TABLE xml_staging (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    xml_data     CLOB,
    status       VARCHAR2(20) DEFAULT 'NEW',
    error_msg    VARCHAR2(1000),
    created_at   DATE DEFAULT SYSDATE
);

INSERT INTO xml_staging (xml_data)
VALUES ('<?xml version="1.0" encoding="UTF-8"?>
<doc>
    <taxpayer>
        <name>Ivan Ivanov</name>
        <egn>1234567890</egn>
        <type>1</type>
        <bulstat>1234567890</bulstat>
        <caddress>Sofia</caddress>
    </taxpayer>
    <hasrepresentative>true</hasrepresentative>
    <representative>
        <name>Petar Petrov</name>
        <egn>9876543210</egn>
        <type>2</type>
    </representative>
    <docs>
        <docenum>
            <id>DOC1</id>
            <fields>
                <field>
                    <name>field1</name>
                    <value>value1</value>
                </field>
            </fields>
        </docenum>
    </docs>
    <reason>Test</reason>
    <email>test@test.com</email>
</doc>');

commit;

CREATE OR REPLACE PROCEDURE load_xml_bulk IS

    v_err_msg VARCHAR2(1000);

BEGIN

    -------------------------------------------------
    -- 0. RESET NEW → VALID (ще филтрираме после)
    -------------------------------------------------
    UPDATE xml_staging
    SET status = 'VALID',
        error_msg = NULL
    WHERE status = 'NEW';

    -------------------------------------------------
    -- 2. XSD VALIDATION (ако имаш schema)
    -------------------------------------------------
--    UPDATE xml_staging s
--    SET status = 'ERROR',
--        error_msg = 'XSD validation failed'
--    WHERE status = 'VALID'
--      AND EXISTS (
--        SELECT 1
--        FROM dual
--        WHERE XMLTYPE(s.xml_data, 'doc_schema.xsd').isSchemaValid() = 0
--    );

    -------------------------------------------------
    -- 3. BUSINESS VALIDATIONS
    -------------------------------------------------

    -- hasrepresentative
    UPDATE xml_staging s
    SET status = 'ERROR',
        error_msg = 'Invalid hasrepresentative'
    WHERE status = 'VALID'
      AND EXISTS (
        SELECT 1
        FROM XMLTABLE(
            '/doc'
            PASSING XMLTYPE(s.xml_data)
            COLUMNS hasrep VARCHAR2(10) PATH 'hasrepresentative'
        ) x
        WHERE LOWER(TRIM(x.hasrep)) NOT IN ('true','false')
    );

    -- email
    UPDATE xml_staging s
    SET status = 'ERROR',
        error_msg = 'Invalid email'
    WHERE status = 'VALID'
      AND EXISTS (
        SELECT 1
        FROM XMLTABLE(
            '/doc'
            PASSING XMLTYPE(s.xml_data)
            COLUMNS email VARCHAR2(200) PATH 'email'
        ) x
        WHERE NOT REGEXP_LIKE(x.email, '^[^@]+@[^@]+\.[^@]+$')
    );

    -- taxpayer type
    UPDATE xml_staging s
    SET status = 'ERROR',
        error_msg = 'Invalid taxpayer type'
    WHERE status = 'VALID'
      AND EXISTS (
        SELECT 1
        FROM XMLTABLE(
            '/doc/taxpayer'
            PASSING XMLTYPE(s.xml_data)
            COLUMNS type NUMBER PATH 'type'
        ) x
        WHERE x.type NOT IN (1,2)
    );

    -- EGN
    UPDATE xml_staging s
    SET status = 'ERROR',
        error_msg = 'Invalid EGN'
    WHERE status = 'VALID'
      AND EXISTS (
        SELECT 1
        FROM XMLTABLE(
            '/doc/taxpayer'
            PASSING XMLTYPE(s.xml_data)
            COLUMNS egn VARCHAR2(20) PATH 'egn'
        ) x
        WHERE NOT REGEXP_LIKE(x.egn, '^[0-9]{10}$')
    );

    -- representative logic
    UPDATE xml_staging s
    SET status = 'ERROR',
        error_msg = 'Representative not allowed'
    WHERE status = 'VALID'
      AND EXISTS (
        SELECT 1
        FROM XMLTABLE(
            '/doc'
            PASSING XMLTYPE(s.xml_data)
            COLUMNS
                hasrep VARCHAR2(10) PATH 'hasrepresentative',
                rep XMLTYPE PATH 'representative'
        ) t
        WHERE LOWER(TRIM(t.hasrep)) = 'false'
          AND t.rep IS NOT NULL
    );

    -------------------------------------------------
    -- 4. DOCUMENTS (само VALID!)
    -------------------------------------------------
    INSERT INTO x_documents (doc_id, staging_id, reason, email, has_rep)
    SELECT x_seq_documents.NEXTVAL,
           s.id,
           x.reason,
           x.email,
           CASE LOWER(TRIM(x.hasrep)) WHEN 'true' THEN 'Y' ELSE 'N' END
    FROM xml_staging s
    CROSS JOIN XMLTABLE(
        '/doc'
        PASSING XMLTYPE(s.xml_data)
        COLUMNS
            reason VARCHAR2(200) PATH 'reason',
            email  VARCHAR2(200) PATH 'email',
            hasrep VARCHAR2(10)  PATH 'hasrepresentative'
    ) x
    WHERE s.status = 'VALID';

    -------------------------------------------------
    -- 5. TAXPAYER
    -------------------------------------------------
    INSERT INTO x_taxpayers (doc_id, name, egn, type, bulstat, address)
    SELECT d.doc_id,
           x.name, x.egn, x.type, x.bulstat, x.caddress
    FROM xml_staging s
    JOIN x_documents d ON d.staging_id = s.id
    CROSS JOIN XMLTABLE(
        '/doc/taxpayer'
        PASSING XMLTYPE(s.xml_data)
        COLUMNS
            name     VARCHAR2(200) PATH 'name',
            egn      VARCHAR2(20)  PATH 'egn',
            type     NUMBER        PATH 'type',
            bulstat  VARCHAR2(20)  PATH 'bulstat',
            caddress VARCHAR2(500) PATH 'caddress'
    ) x
    WHERE s.status = 'VALID';

    -------------------------------------------------
    -- 6. REPRESENTATIVE (fixed version)
    -------------------------------------------------
    INSERT INTO x_representatives (doc_id, name, egn, type)
    SELECT d.doc_id,
           x.name,
           x.egn,
           x.type
    FROM xml_staging s
    JOIN x_documents d ON d.staging_id = s.id
    CROSS JOIN XMLTABLE(
        '/doc'
        PASSING XMLTYPE(s.xml_data)
        COLUMNS
            hasrep VARCHAR2(10) PATH 'hasrepresentative',
            name   VARCHAR2(200) PATH 'representative/name',
            egn    VARCHAR2(20)  PATH 'representative/egn',
            type   NUMBER        PATH 'representative/type'
    ) x
    WHERE s.status = 'VALID'
      AND LOWER(TRIM(x.hasrep)) = 'true'
      AND x.name IS NOT NULL;

    -------------------------------------------------
    -- 7. DOCENUM
    -------------------------------------------------
    INSERT INTO x_doc_enums (docenum_id, doc_id, ext_id)
    SELECT x_seq_docenum.NEXTVAL,
           d.doc_id,
           x.id
    FROM xml_staging s
    JOIN x_documents d 
        ON d.staging_id = s.id
    CROSS JOIN XMLTABLE(
        '/doc/docs/docenum'
        PASSING XMLTYPE(s.xml_data)
        COLUMNS
            id VARCHAR2(100) PATH 'id'
    ) x
    WHERE s.status = 'VALID';

    -------------------------------------------------
    -- 8. FIELDS
    -------------------------------------------------
    INSERT INTO x_doc_fields (docenum_id, name, value)
    SELECT de.docenum_id,
           f.name,
           f.value
    FROM xml_staging s
    JOIN x_documents d 
        ON d.staging_id = s.id
    JOIN x_doc_enums de 
        ON de.doc_id = d.doc_id
    CROSS JOIN XMLTABLE(
        '/doc/docs/docenum'
        PASSING XMLTYPE(s.xml_data)
        COLUMNS
            id         VARCHAR2(100) PATH 'id',
            fields_xml XMLTYPE       PATH 'fields'
    ) x
    CROSS JOIN XMLTABLE(
        '/fields/field'
        PASSING x.fields_xml
        COLUMNS
            name  VARCHAR2(200) PATH 'name',
            value VARCHAR2(500) PATH 'value'
    ) f
    WHERE s.status = 'VALID'
      AND de.ext_id = x.id;
    -------------------------------------------------
    -- 9. MARK DONE
    -------------------------------------------------
    UPDATE xml_staging
    SET status = 'DONE'
    WHERE status = 'VALID';

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        v_err_msg := SUBSTR(SQLERRM,1,1000);

        UPDATE xml_staging
        SET status = 'ERROR',
            error_msg = v_err_msg
        WHERE status IN ('NEW','VALID');

        COMMIT;
END;
/

BEGIN
  load_xml_bulk;
END;
/

SELECT * FROM x_documents;
SELECT * FROM x_taxpayers;
SELECT * FROM x_representatives;
SELECT * FROM x_doc_enums;
SELECT * FROM x_doc_fields;
select * from xml_staging